apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170546884
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170546884
    app.kubernetes.io/part-of: test-app-170546884
  name: java-quarkus-170546884
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170546884
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170546884
    spec:
      containers:
      - image: quay.io/hacdev/flt8zapo-tenant/test-app-170546884/java-quarkus-170546884@sha256:49ec2d8bb6c23546dfd2b783334c10a4d68489fbb03e9bafde3fac9bed88230d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
